config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    member do
      patch :move
    end
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end
  # mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	acts_as_list
	has_many :technologies
	accepts_nested_attributes_for :technologies,
			allow_destroy: true,
			reject_if: lambda {|attrs| attrs['name'].blank? }
	
	validates :title, :body, presence: true
	
	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	def self.angular
		where(subtitle: 'Angular')
	end

	def self.by_position
		order("position ASC")
	end

	scope :ruby_on_rails, -> {where(subtitle: 'Ruby on Rails')}
end


# ||= it's a shortcut of the following notation
# if self.main_image == nil
		# self.main_image = "http://www.placehold.it/600x400"
# end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio, only: %i[ show edit update destroy move]
	layout "portfolio"
	access all: [:show, :index, :angular], user: {except: [:destroy, :new, :update, :create, :edit, :move]}, site_admin: :all

	def index
		@portfolio_items = Portfolio.by_position
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end
	def show
		
	end
	def edit
	end

	def new
		@portfolio_item = Portfolio.new
	end
	def create
	    @portfolio_item = Portfolio.new(portfolio_params)

	    respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portfolios_path, notice: "Your portfolio was successfully created." }
	      else
	        format.html { render :new, status: :unprocessable_entity }
	      end
	    end
  	end

  	def update
	    respond_to do |format|
	      if @portfolio_item.update(portfolio_params)
	        format.html { redirect_to portfolios_path, notice: "Your portfolio item was successfully updated." }
	      else
	        format.html { render :edit, status: :unprocessable_entity }
	      end
	    end
	end
	def destroy
		#Perform lookup
	 	# @portfolio_item = Portfolio.find(params[:id])	 moved to portfolio_params
		#destroy the record
		@portfolio_item.destroy

		#redicrect
    	respond_to do |format|
		    format.html { redirect_to portfolios_url, notice: "Record was successfully removed." }
  		end
	end

	def move
		@portfolio_item.insert_at(params[:position].to_i)
	end

	private
	
		def set_portfolio
		 	@portfolio_item = Portfolio.find(params[:id])	
		end
	  def portfolio_params
	    params.require(:portfolio).permit(
	    	:title, 
	    	:subtitle, 
	    	:body, 
	    	:main_image, 
	    	:thumb_image, 
	    	technologies_attributes: [:id, :name, :_destroy]
	    	)
	  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  	def image_generator(height:, width:)
		"https://via.placeholder.com/#{height}x#{width}"
	end

	def portfolio_img img, type
		if img.model.main_image? || img.model.thumb_image?
		  img.to_s
		elsif type == 'thumb'
		  image_generator(height: '350', width: '200')
		elsif type == 'main'
		  image_generator(height: '600', width: '400')
		end
	end
	# def portfolio_img item, type
	#     if type == 'thumb'
	#         item.thumb_image.url || image_generator(height: '350', width: '200')
	#     else # 'main'
	#         item.main_image.url || image_generator(height: '600', width: '400')
	#     end
	# end
end

# self.main_image ||= Placeholder.image_generator(height: '600',width: '400')
# self.thumb_image ||= Placeholder.image_generator(height: '350',width: '200')

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %> %>
    <% end %>
  <% end %>
 <div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control top-buffer' %>
    </div> 
    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle , class: 'form-control top-buffer'%>
    </div>
    <div class="form-group top-buffer">
      <label class="btn btn-primary">
        Upload a main image file<%= form.file_field :main_image, style: 'display:none' %>
      </label>
    </div>
    <div class="form-group top-buffer">
      <label class="btn btn-primary">
        Upload a thumb image file<%= form.file_field :thumb_image, style: 'display:none' %>
      </label>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control top-buffer', rows:8 %>
    </div>
  </div>

    <hr class="top-buffer">
  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :technologies do |technology| %>
        <%= render 'technology_fields', f: technology %>
      <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', form, :technologies %>
      </div>
    </div>

    <div class="form-group d-grid gap-2 mx-auto">
      <%= form.submit "Save Portfolio Item", class: 'top-buffer btn btn-primary'%>
    </div>
  </div>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card shadow-sm" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
  <div class="card-body">
    <p class="card-text">
    	<span><%= portfolio_item.title %></span>
    	<%= portfolio_item.subtitle %>
    </p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
      	<%= link_to "View", portfolio_show_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
      	<%= link_to "Edit", edit_portfolio_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary'  if logged_in?(:site_admin)%>
      </div>

    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control top-buffer'%>
    <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin)%>

<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%=  link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
	<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
	<h1>Edit a new Portfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>

	<%= link_to 'Show', portfolio_show_path(@portfolio_item) %> |
	<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" <%= "data-controller=drag data-drag-url=/portfolios/:id/move" if logged_in?(:site_admin) %>>

			<%= render partial: 'portfolio_item', collection: @portfolio_items %>

		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
	<h1>Create a new Portfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>

	<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
	<div class="row portfolio-container">
		<div class="col-md-7">
			<%= image_tag portfolio_img(@portfolio_item.thumb_image, 'main'), width: '100%' %>	
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>
			<hr>
			<em><%= @portfolio_item.subtitle %></em>
			<p><%= @portfolio_item.body %></p>

			<hr>
			<h3>Technologies Used:</h3>
			<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %> </p>
			<% end %>

			<% if logged_in?(:site_admin) %>
				<div class="col-md-12">
					<%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
				</div>
			<% end %>
		</div>
	</div>
</div>