config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    member do
      patch :move
    end
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end
  # mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], :title => "Przemek Zastawny Portfolio", :sticky => false, :time => 1000, :class_name => "custom_gritter") %>
<% elsif flash[:error] %>
	<%= js add_gritter(flash[:error], :title => "Przemek Zastawny Portfolio", :sticky => false, :time => 1000, :class_name => "custom_gritter") %>
<% else %>
	<%= js add_gritter(flash[:notice], :title => "Przemek Zastawny Portfolio", :sticky => false, :time => 1000, :class_name => "custom_gritter") %>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="mt-auto app-footer">
  <p><%= @copyright %></p>
</footer>

app/views/shared/_application_nav.html.erb
<header>
<div class="masthead clearfix">
  <div class="inner">
    <nav class="nav nav-masthead app-nav">
    <h3 class="masthead-brand">Przemek Zastawny</h3>
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= @copyright%></p>
  <p>
    <a href="#" class="btn">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span><%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %></span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light blog-nav">
  <div class="container">
  <%= link_to "Przemek Zastawny", root_path, class: 'navbar-brand d-flex align-items-center' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
   <p><%= source_helper("alert alert-info") %></p>


  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <p class="fa_icon('bullet')"><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    	<%= link_to "View All Portfolio Items", portfolios_path %>
      <a href="#" class='btn'>Back to top</a>
    </p>
  <p><%= @copyright%></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">My portfolio</h1>
      <p class="lead text-muted">I hope to populate it with some cool stuff soon.</p>
      <p>
        <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
        <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
      </p>
    </div>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">In daily work I mostly write VBA and Google app scripts. Since few weeks I started to learn Ruby on Rails, which is quite handy.</p>
        </div>
        <div class="col-sm-4 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
						<li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">

        <strong>Przemek Zastawny</strong>
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
  </div>
</header>